<script src="https://cdn-fc.com/creatives/bar/bar.min.js?v=1742148239"></script>
<script>
var text={
'en': '<span>😍 Watch and download FULL videos in HD & 4K quality 🔥</span> <span class="fh-button fh-button3">GET ACCESS</span>',
'de': '<span>😍 Schau und lade VOLLE Videos in HD- & 4K-Qualität herunter 🔥</span> <span class="fh-button fh-button3">ZUGANG ERHALTEN</span>',
'id': '<span>😍 Tonton dan unduh video PENUH dalam kualitas HD & 4K 🔥</span> <span class="fh-button fh-button3">DAPATKAN AKSES</span>',
'jv': '<span>😍 Nonton lan ngundhuh video LENGKAP kanthi kualitas HD & 4K 🔥</span> <span class="fh-button fh-button3">ENTUK AKSES</span>',
'su': '<span>😍 Tonton jeung unduh pidio LENGKAP dina kualitas HD & 4K 🔥</span> <span class="fh-button fh-button3">CANDak AKSÉS</span>',
'ta': '<span>😍 HD & 4K தரத்தில் முழு வீடியோக்களை பாருங்கள் மற்றும் பதிவிறக்குங்கள் 🔥</span> <span class="fh-button fh-button3">அணுகலை பெற</span>',
'te': '<span>😍 HD & 4K నాణ్యతలో పూర్తి వీడియోలను చూడండి మరియు డౌన్‌లోడ్ చేయండి 🔥</span> <span class="fh-button fh-button3">ప్రవేశం పొందండి</span>',
'mr': '<span>😍 HD आणि 4K गुणवत्तेत FULL व्हिडिओ पाहा आणि डाउनलोड करा 🔥</span> <span class="fh-button fh-button3">प्रवेश मिळवा</span>',
'gu': '<span>😍 HD અને 4K ગુણવત્તામાં FULL વિડિયો જુઓ અને ડાઉનલોડ કરો 🔥</span> <span class="fh-button fh-button3">પ્રવેશ મેળવો</span>',
'pa': '<span>😍 HD ਅਤੇ 4K ਕੁਆਲਿਟੀ ਵਿੱਚ FULL ਵੀਡੀਓ ਵੇਖੋ ਤੇ ਡਾਊਨਲੋਡ ਕਰੋ 🔥</span> <span class="fh-button fh-button3">ਐਕਸੈੱਸ ਲਵੋ</span>',
'hi': '<span>😍 HD और 4K क्वालिटी में FULL वीडियो देखें और डाउनलोड करें 🔥</span> <span class="fh-button fh-button3">एक्सेस पाएं</span>',
'bn': '<span>😍 HD ও 4K মানে FULL ভিডিও দেখুন এবং ডাউনলোড করুন 🔥</span> <span class="fh-button fh-button3">এ্যাক্সেস নিন</span>',
'ml': '<span>😍 HD & 4K ഗുണമേന്മയിൽ FULL വീഡിയോകൾ കാണൂ, ഡൗൺലോഡ് ചെയ്യൂ 🔥</span> <span class="fh-button fh-button3">പ്രവേശനം നേടുക</span>',
'kn': '<span>😍 HD ಮತ್ತು 4K ಗುಣಮಟ್ಟದಲ್ಲಿ FULL ವೀಡಿಯೊಗಳನ್ನು ನೋಡಿ ಮತ್ತು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ 🔥</span> <span class="fh-button fh-button3">ಪ್ರವೇಶ ಪಡೆಯಿರಿ</span>',
'or': '<span>😍 HD ଏବଂ 4K ଗୁଣବତ୍ତାରେ FULL ଭିଡିଓ ଦେଖନ୍ତୁ ଏବଂ ଡାଉନଲୋଡ୍ କରନ୍ତୁ 🔥</span> <span class="fh-button fh-button3">ଅଭିଗମ ପାଆନ୍ତୁ</span>',
'as': '<span>😍 HD আৰু 4K গুণগতাত FULL ভিডিও চাওক আৰু ডাউনল’ড কৰক 🔥</span> <span class="fh-button fh-button3">এক্সেছ লাভ কৰক</span>',
'ne': '<span>😍 HD र 4K गुणस्तरमा FULL भिडियो हेर्नुहोस् र डाउनलोड गर्नुहोस् 🔥</span> <span class="fh-button fh-button3">प्रवेश पाउनुहोस्</span>',
'ur': '<span>😍 HD اور 4K کوالٹی میں FULL ویڈیوز دیکھیں اور ڈاؤن لوڈ کریں 🔥</span> <span class="fh-button fh-button3">رسائی حاصل کریں</span>',
'tl': '<span>😍 Manood at mag-download ng FULL videos sa HD at 4K na kalidad 🔥</span> <span class="fh-button fh-button3">KUNIN ANG ACCESS</span>',
'ceb': '<span>😍 Tan-awa ug i-download ang FULL videos sa HD ug 4K nga kalidad 🔥</span> <span class="fh-button fh-button3">KUHAA ANG ACCESS</span>',
'ilo': '<span>😍 Biroken ken i-download dagiti FULL a video iti HD ken 4K a kinalaing 🔥</span> <span class="fh-button fh-button3">ALAEN TI ACCESS</span>',
'es': '<span>😍 Mira y descarga videos COMPLETOS en calidad HD y 4K 🔥</span> <span class="fh-button fh-button3">OBTENER ACCESO</span>',
'nah': '<span>😍 Xittaz itta uān xitlāxilōti FULL tlācatl video īpan HD īhuān 4K cualtīlli 🔥</span> <span class="fh-button fh-button3">XIGRĀPI ĀXCES</span>',
'my': '<span>😍 HD နှင့် 4K အရည်အပြည့် FULL ဗီဒီယိုများကို ကြည့်ပြီး ဒေါင်းလုပ်လုပ်ပါ 🔥</span> <span class="fh-button fh-button3">အသုံးပြုခွင့်ယူရန်</span>',
'vi': '<span>😍 Xem và tải FULL video chất lượng HD & 4K 🔥</span> <span class="fh-button fh-button3">NHẬN QUYỀN TRUY CẬP</span>',
'km': '<span>😍 មើល និងទាញយកវីដេអូពេញលេញគុណភាព HD និង 4K 🔥</span> <span class="fh-button fh-button3">ទទួលការចូលដំណើរការ</span>',
'fr': '<span>😍 Regardez et téléchargez des vidéos COMPLÈTES en qualité HD et 4K 🔥</span> <span class="fh-button fh-button3">OBTENIR L’ACCÈS</span>',
'ms': '<span>😍 Tonton dan muat turun video PENUH dalam kualiti HD & 4K 🔥</span> <span class="fh-button fh-button3">DAPATKAN AKSES</span>',
'zh': '<span>😍 观看并下载高清与4K画质的完整视频 🔥</span> <span class="fh-button fh-button3">获取访问</span>',
'th': '<span>😍 ดูและดาวน์โหลดวิดีโอแบบเต็มคุณภาพ HD และ 4K 🔥</span> <span class="fh-button fh-button3">ขอสิทธิ์เข้าถึง</span>',
'ku': '<span>😍 Vîdyoyên TEWRE bi kêşeya HD û 4K seyr û daxîne 🔥</span> <span class="fh-button fh-button3">DESTPEKÊ WERBIGRE</span>',
'pt': '<span>😍 Assista e baixe vídeos COMPLETOS em qualidade HD e 4K 🔥</span> <span class="fh-button fh-button3">OBTER ACESSO</span>',
'nl': '<span>😍 Bekijk en download VOLLEDIGE video’s in HD- & 4K-kwaliteit 🔥</span> <span class="fh-button fh-button3">TOEGANG KRIJGEN</span>',
'sr': '<span>😍 Гледај и преузми ПУНЕ видео записе у HD и 4K квалитету 🔥</span> <span class="fh-button fh-button3">ДОБИЈ ПРИСТУП</span>',
'uk': '<span>😍 Дивіться та завантажуйте ПОВНІ відео в якості HD і 4K 🔥</span> <span class="fh-button fh-button3">ОТРИМАТИ ДОСТУП</span>',
'pl': '<span>😍 Oglądaj i pobieraj PEŁNE filmy w jakości HD i 4K 🔥</span> <span class="fh-button fh-button3">UZYSKAJ DOSTĘP</span>',
'sv': '<span>😍 Titta på och ladda ner FULLA videor i HD- och 4K-kvalitet 🔥</span> <span class="fh-button fh-button3">FÅ ÅTKOMST</span>',
'fi': '<span>😍 Katso ja lataa TÄYDET videot HD- ja 4K-laadulla 🔥</span> <span class="fh-button fh-button3">HANKI KÄYTTÖOIKEUS</span>',
'da': '<span>😍 Se og download FULDE videoer i HD- og 4K-kvalitet 🔥</span> <span class="fh-button fh-button3">FÅ ADGANG</span>',
'no': '<span>😍 Se og last ned FULL video i HD- og 4K-kvalitet 🔥</span> <span class="fh-button fh-button3">FÅ TILGANG</span>',
'is': '<span>😍 Horfðu á og sæktu FULL myndbönd í HD- og 4K-gæðum 🔥</span> <span class="fh-button fh-button3">FÁ AÐGANG</span>',
'lv': '<span>😍 Skaties un lejupielādē PILNUS video HD un 4K kvalitātē 🔥</span> <span class="fh-button fh-button3">IEGŪT PIEKĻUVI</span>',
'hu': '<span>😍 Nézz és tölts le TELJES videókat HD és 4K minőségben 🔥</span> <span class="fh-button fh-button3">HOZZÁFÉRÉS KÉRÉSE</span>',
'af': '<span>😍 Kyk en laai VOL video’s af in HD- en 4K-gehalte 🔥</span> <span class="fh-button fh-button3">KRY TOEGANG</span>',
'zu': '<span>😍 Buka futhi ulande amavidiyo AGCWELE ngekhwalithi ye-HD ne-4K 🔥</span> <span class="fh-button fh-button3">THOLA UKUNGENA</span>',
'xh': '<span>😍 Bukela kwaye ukhuphele iividiyo EZIZEZIZEGQITHISILEYO kumgangatho we-HD ne-4K 🔥</span> <span class="fh-button fh-button3">FUMANA UFikelelo</span>',
'st': '<span>😍 Shebella le ho jarolla livideo TSE FELletseng ka boleng ba HD le 4K 🔥</span> <span class="fh-button fh-button3">FUMANA PHIHLELLO</span>',
'cs': '<span>😍 Sledujte a stahujte PLNÁ videa v kvalitě HD a 4K 🔥</span> <span class="fh-button fh-button3">ZÍSKAT PŘÍSTUP</span>',
'ru': '<span>😍 Смотрите и скачивайте ПОЛНЫЕ видео в качестве HD и 4K 🔥</span> <span class="fh-button fh-button3">ПОЛУЧИТЬ ДОСТУП</span>',
'ja': '<span>😍 HD・4K品質のフル動画を視聴＆ダウンロード 🔥</span> <span class="fh-button fh-button3">アクセスを取得</span>',
'ro': '<span>😍 Urmărește și descarcă videoclipuri COMPLETE la calitate HD & 4K 🔥</span> <span class="fh-button fh-button3">OBȚINE ACCES</span>',
'ar': '<span>😍 شاهد وحمّل مقاطع فيديو كاملة بجودة HD و4K 🔥</span> <span class="fh-button fh-button3">احصل على الوصول</span>',
'ps': '<span>😍 په HD او 4K کیفیت کې پوره وېډیوګانې وګورئ او ښکته یې کړئ 🔥</span> <span class="fh-button fh-button3">لاس‌رسی ترلاسه کړئ</span>',
'fa': '<span>😍 ویدیوهای کامل را با کیفیت HD و 4K تماشا و دانلود کنید 🔥</span> <span class="fh-button fh-button3">دسترسی بگیر</span>',
'sd': '<span>😍 HD ۽ 4K معيار ۾ FULL وڊيوز ڏسو ۽ ڊائونلوڊ ڪريو 🔥</span> <span class="fh-button fh-button3">رسائي حاصل ڪريو</span>',
'si': '<span>😍 HD සහ 4K ගුණත්වයෙන් පූර්ණ වීඩියෝ නැරඹීම හා බාගත කිරීම 🔥</span> <span class="fh-button fh-button3">ප්‍රවේශය ලබාගන්න</span>',
'ber': '<span>😍 Wali sy ddɣi-d tividyutin IMMMIDEN s tɣara HD d 4K 🔥</span> <span class="fh-button fh-button3">Awi anekcum</span>',
'ha': '<span>😍 Kalla ka zazzage cikakkun bidiyoyi a ingancin HD da 4K 🔥</span> <span class="fh-button fh-button3">SAMU DAMA</span>',
'ga': '<span>😍 Féach agus íosluchtaigh FÍOR-físeáin i gcáilíocht HD & 4K 🔥</span> <span class="fh-button fh-button3">FAIGH ROCHTAIN</span>',
'be': '<span>😍 Глядзіце і спампоўвайце Поўныя відэа ў якасці HD і 4K 🔥</span> <span class="fh-button fh-button3">АТРЫМАЦЬ ДОСТУП</span>',
'lt': '<span>😍 Žiūrėkite ir atsisiųskite PILNUS vaizdo įrašus HD ir 4K kokybe 🔥</span> <span class="fh-button fh-button3">GAUTI PRIEIGĄ</span>',
'mk': '<span>😍 Гледај и симни ПОЛНИ видеа во HD и 4K квалитет 🔥</span> <span class="fh-button fh-button3">ДОБИЈ ПРИСТАП</span>',
'sr-latin': '<span>😍 Gledaj i preuzmi PUNE video snimke u HD i 4K kvalitetu 🔥</span> <span class="fh-button fh-button3">DOBIJ PRISTUP</span>',
'sq': '<span>😍 Shiko dhe shkarko video të PLOTA në cilësi HD & 4K 🔥</span> <span class="fh-button fh-button3">MERR AKSES</span>',
'bg': '<span>😍 Гледайте и изтегляйте ПЪЛНИ видеа в HD и 4K качество 🔥</span> <span class="fh-button fh-button3">ВЗЕМИ ДОСТЪП</span>',
'hr': '<span>😍 Gledaj i preuzmi PUNE videozapise u HD i 4K kvaliteti 🔥</span> <span class="fh-button fh-button3">DOBIJ PRISTUP</span>',
'sk': '<span>😍 Pozerajte a sťahujte PLNÉ videá v kvalite HD a 4K 🔥</span> <span class="fh-button fh-button3">ZÍSKAŤ PRÍSTUP</span>',
'cy': '<span>😍 Gwyliwch a lawrlwythwch FIDEOEDD LLAWN mewn ansawdd HD a 4K 🔥</span> <span class="fh-button fh-button3">CAEL MYNEDIAD</span>',
'eu': '<span>😍 Ikusi eta deskargatu BIDEO OSOAK HD eta 4K kalitatean 🔥</span> <span class="fh-button fh-button3">ESKURATU SARBIDEA</span>',
'gl': '<span>😍 Mira e descarga vídeos COMPLETOS en calidade HD e 4K 🔥</span> <span class="fh-button fh-button3">OBTER ACCESO</span>',
'el': '<span>😍 Δες και κατέβασε ΠΛΗΡΗ βίντεο σε ποιότητα HD & 4K 🔥</span> <span class="fh-button fh-button3">ΑΠΟΚΤΗΣΕ ΠΡΟΣΒΑΣΗ</span>',
'tr': '<span>😍 HD & 4K kalitede TAM videoları izle ve indir 🔥</span> <span class="fh-button fh-button3">ERİŞİM AL</span>'
};

var barStyle = '@media (max-width:700px){.fh-line1,.fh-line2,.fh-line3,.fh-line4{padding:3px 0 5px;background-size:cover;font-size:14px;line-height:20px}.fh-button{display:none}}';
  
var options = {
    url: 'https://fhgte.com/tour?utm_campaign=ai.tYZ&utm_content=lickingassholes.com_bar_under_player',
    defaultLang: 'en',
    target: '_blank',
    rel: 'nofollow',
    marginClass: 'fh-margin',
    designClass: 'fh-line2',
    style: barStyle
};
  
banner.init(text, options);
</script>